In [1]:
smash = ['Mario', 'DK', 'Link', 'Samus','Yoshi','Kirby', 'Fox', 'Pikachu']

In [2]:
smash

['Mario', 'DK', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']

In [3]:
smash += ['Luigi','Ness', 'C. Falcon', 'Jigglypuff']

In [4]:
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff']

In [5]:
smash += [['Metal Mario', 'Polygon Team', 'Master Hand']]

In [6]:
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [10]:
smash = ['Mario', 'DK', 'Link', 'Samus','Yoshi','Kirby', 'Fox', 'Pikachu']

In [11]:
smash += ['Luigi','Ness', 'C. Falcon', 'Jigglypuff']

In [12]:
smash += [['Metal Mario', 'Polygon Team', 'Master Hand']]

In [13]:
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [14]:
del smash[:8]

In [15]:
smash

['Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [16]:
smash.insert(0,'Original roster')

In [17]:
smash

['Original roster',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [18]:
def null_matrix(M,N):
    return [[[0] * N] * M]

In [19]:
null_matrix(3,4)

[[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]

In [20]:
[[['?'] * 2] * 3] * 4

[[[['?', '?'], ['?', '?'], ['?', '?']],
  [['?', '?'], ['?', '?'], ['?', '?']],
  [['?', '?'], ['?', '?'], ['?', '?']],
  [['?', '?'], ['?', '?'], ['?', '?']]]]

In [21]:
[[['?'] * 2] * 3] * 4

[[['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']]]

In [2]:
mensualidad = {'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}

In [3]:
mensualidad

{'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}

In [4]:
mensualidad.pop('Disney+')
mensualidad['Netflix'] = 139
mensualidad['Prime'] = 99
mensualidad['Blim'] = 109
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109}

In [5]:
mensualidad['Tec'] = 20400
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109, 'Tec': 20400}

In [2]:
import numpy as np

raw = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
raw

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
raw[:2,1:3]

array([[2, 3],
       [6, 7]])

In [12]:
raw[1:4, 2:4]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [3]:
features = raw[:,:3]
labels = raw[:,3:].flatten()
features

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [4]:
labels

array([ 4,  8, 12, 16])

In [5]:
data = list(zip(features,labels))

In [6]:
data

[(array([1, 2, 3]), 4),
 (array([5, 6, 7]), 8),
 (array([ 9, 10, 11]), 12),
 (array([13, 14, 15]), 16)]

In [7]:
test = data[:1]
train = data[1:4]
test

[(array([1, 2, 3]), 4)]

In [8]:
train

[(array([5, 6, 7]), 8), (array([ 9, 10, 11]), 12), (array([13, 14, 15]), 16)]

In [9]:
#16.) prob es .35/.7=0.5

In [10]:
#17.) prob es 0.1*0.99 = 0.099

In [11]:
#18.) Respuesta -2x^4 sin(x^2) + 3x^2 cos(x^2)

In [12]:
#19.) Respuesta 2x sin(x) + x^2 cos(x) + 4x^3

In [ ]:
#20.) Respecto a x 3x^2 + 2xz + z^2 Respecto a z x^2 + 2zx + 3z^2